#!/bin/bash

############################################################
# Help                                                     #
############################################################
Help()
{
   # Display Help
   echo "Setup NVMe kernel module configurations."
   echo
   echo "Syntax: config_nvme_queues.sh [-h|-p|-w|-r|-i|-d]"
   echo "options:"
   echo "-h     Print this Help."
   echo "-p     Set NVMe polling qeueues (4 queues)."
   echo "-w     Set NVMe write qeueues (auto detected)."
   echo "-t     Set NVMe use threaded interrupts."
   echo "-r     Remove all options."
   echo "-i     Install config in /etc/modprobe.d/"
   echo "-d     Display current NVMe module configurations."
   echo
}

echo "Setting NVMe kernel module configurations"
echo

# declare defaults
nvme_caps=`dmesg|grep nvme0|grep 'default\/read\/poll'|awk '{print $ (NF - 2)}'`
write_q_size=${nvme_caps::1}
polling_q_size=4
polling_args=""
write_queue_args=""
interrupts_args=""
remove_args=0
install_conf=0
display_conf=0
nvme_option_string=""
nvme_string="options nvme "

# Get the options
while getopts ':pwtridh' option; do
    case $option in
        h) # display Help
          Help
          exit;;
        p) # set NVMe device polling
          echo "NVMe polling queues enabled"
          polling_args="poll_queues=4 ";;
        w) # set NVMe device write queues
          echo "NVMe $write_q_size write queues enabled"
          write_queue_args="write_queues=$write_q_size ";;
        t) # set NVMe to use threaded interrupts
          echo "NVMe use_threaded_interrupts enabled"
          interrupts_args="use_threaded_interrupts=1 ";;
        r) # remove NVMe device configuration
          echo "Removing all configurations"
          remove_args=1;;
        i) # do not install config file
          echo "Installing nvme.conf in /etc/modprobe.d/"
          install_conf=1;;
        d) # display current config
          echo "Display current configuration from sysfs"
          display_conf=1;;
        \?) # Invalid option
          echo "Error: Invalid option"
          Help
          exit;;
    esac
done

echo

# if no options exit
if [[ $# == 0 ]];then
  echo "Error: no options provided"
  echo
  Help
  exit
fi 

# check current config 
if [[ $display_conf == 1 ]];then
  echo "NVme kernel module config from sysfs: "
  echo
  echo "Polling queues `cat /sys/module/nvme/parameters/poll_queues`"
  echo "Write queues `cat /sys/module/nvme/parameters/write_queues`"
  echo "I/O queue depth `cat /sys/module/nvme/parameters/io_queue_depth`"
  echo
fi

# add polling queues
if [[ -n $polling_args ]];then
  nvme_option_string+=$polling_args
fi

# add wirte queues
if [[ -n $write_queue_args ]];then
  nvme_option_string+=$write_queue_args
fi

# add use_threaded_interrupts
if [[ -n $interrupts_args ]];then
  nvme_option_string+=$interrupts_args
fi

# create full option setting
nvme_string+=$nvme_option_string

# remove all options
if [[ $remove_args == 1 ]];then
  nvme_string=""
fi

# generate nvme kernel module config file
cat << EOF > nvme.conf
# Generated by Opti-Disk
$nvme_string
EOF

if [[ $install_conf == 1 ]];then
  if [[ "$EUID" = 0 ]]; then
    cp nvme.conf /etc/modprobe.d/
    if [[ `cat /etc/issue` == *"Ubuntu"* ]];then
      update-initramfs -u
    fi
  else
    echo "Error cannot install nvme.conf in /etc/modprobe.d, please either run this script using root access, or manually copy nvme.conf."
  fi
fi

echo
echo "Finished configuration for NVMe queues"
